### ISSUE TITLE
Advice re rejected epub files

### ISSUE THREAD

**Issue by Lucky8mate** [mattgarrish/epub-revision#2647] opened 2024-09-04 21:26 UTC
Hi
I am having problems uploading an epub file to Ingramsparks  (fixed not flowing as I am uploading a picture book) as attached. 

I have tried googles epub version, i have tried various conversion software unfortunately their is always a problem. Accordingly can anyone please advise how I can fix this problem. I am open to taking a course.

[epub ingramspark issues.docx](https://github.com/user-attachments/files/16881151/epub.ingramspark.issues.docx)
[epub ingramspark issues.pdf](https://github.com/user-attachments/files/16881152/epub.ingramspark.issues.pdf)

Many thanks

**Comment by iherman** [comment] 2024-09-05 04:04
@Lucky8mate, this repository is dedicated to the technical development and maintenance of the EPUB specification format, and it is not aimed issues related to specific publishers, distributors, or reading systems. I would advise you to contact Ingram directly, or any user community that may exist around Ingram, for help.

Closing this issue as out of scope.

**Closed as completed by iherman** 2024-09-05 04:04 UTC

**Comment by Lucky8mate** [comment] 2024-09-06 15:13
Hi iHerman
Ingram also closed issue as outside of their scope. Onwards and upwards i suppose.

**Comment by mattgarrish** [comment] 2024-09-06 16:07
Some possible alternative locations to ask might be:

- #eprdctn group on x/twitter (although I don't know if it is frequented much anymore)
- the [epub forum](https://www.mobileread.com/forums/forumdisplay.php?f=179) at mobileread
- the [publishing community group](https://github.com/w3c/publishingcg/issues)
- the [ebooks section](https://ebooks.stackexchange.com/questions/tagged/epub) at stackexchange

I wonder if it might be worthwhile to add something like this to the readme for this repository? As in, please go to these other places for general help. Better than leaving people to wonder whether to post here.

(A quick guess for your problem is that they don't allow remote fonts so there is no fix but to remove the include.)

**Comment by Lucky8mate** [comment] 2024-09-06 16:41
> Some possible alternative locations to ask might be:
> 
> * #eprdctn group on x/twitter (although I don't know if it is frequented much anymore)
> * the [epub forum](https://www.mobileread.com/forums/forumdisplay.php?f=179) at mobileread
> * the [publishing community group](https://github.com/w3c/publishingcg/issues)
> * the [ebooks section](https://ebooks.stackexchange.com/questions/tagged/epub) at stackexchange
> 
> I wonder if it might be worthwhile to add something like this to the readme for this repository? As in, please go to these other places for general help. Better than leaving people to wonder whether to post here.
> 
> (A quick guess for your problem is that they don't allow remote fonts so there is no fix but to remove the include.)

Many many thanks

**Comment by iherman** [comment] 2024-09-07 06:34
> 
> I wonder if it might be worthwhile to add something like this to the readme for this repository? As in, please go to these other places for general help. Better than leaving people to wonder whether to post here.

I believe there are some ways to add some prompt text to the 'new issue' button of the repository. I do not know, maybe someone else does (if not, I will try to find out). I do not think that people will read the Readme file before raising an issue.

(Actually: one does not exclude the other.)

**Comment by mattgarrish** [comment] 2024-09-07 13:31
> I believe there are some ways to add some prompt text to the 'new issue' button of the repository.

Ya, good idea! I wasn't even thinking about that, but maybe it would help to have a template for reporting, asking people for specifics like the section number where the problem is.

I think only you can set a template up, though: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
